@ECHO OFF

SET CGO_ENABLED=1
ECHO CGO_ENABLED=%CGO_ENABLED%

SET CC=clang
ECHO CC=%CC%

SET CFLAGS=
ECHO CFLAGS=%CFLAGS%

SET CGO_CFLAGS=-fuse-ld=lld
ECHO CGO_CFLAGS=%CGO_CFLAGS%

SET CGO_CFLAGS_ALLOW=-fuse-ld=lld
ECHO CGO_CFLAGS_ALLOW=%CGO_CFLAGS_ALLOW%

SET LDFLAGS=
ECHO LDFLAGS=%LDFLAGS%

SET CGO_LDFLAGS=-lSDL2
ECHO CGO_LDFLAGS=%CGO_LDFLAGS%

go build -x .

@REM // #cgo CFLAGS: -fuse-ld=lld
@REM // #cgo LDFLAGS: -lSDL2
