package m

type LogCategory = Int

/*
typedef enum

	{
	    SDL_LOG_CATEGORY_APPLICATION,
	    SDL_LOG_CATEGORY_ERROR,
	    SDL_LOG_CATEGORY_ASSERT,
	    SDL_LOG_CATEGORY_SYSTEM,
	    SDL_LOG_CATEGORY_AUDIO,
	    SDL_LOG_CATEGORY_VIDEO,
	    SDL_LOG_CATEGORY_RENDER,
	    SDL_LOG_CATEGORY_INPUT,
	    SDL_LOG_CATEGORY_TEST,

	    SDL_LOG_CATEGORY_RESERVED1,
	    SDL_LOG_CATEGORY_RESERVED2,
	    SDL_LOG_CATEGORY_RESERVED3,
	    SDL_LOG_CATEGORY_RESERVED4,
	    SDL_LOG_CATEGORY_RESERVED5,
	    SDL_LOG_CATEGORY_RESERVED6,
	    SDL_LOG_CATEGORY_RESERVED7,
	    SDL_LOG_CATEGORY_RESERVED8,
	    SDL_LOG_CATEGORY_RESERVED9,
	    SDL_LOG_CATEGORY_RESERVED10,

	    SDL_LOG_CATEGORY_CUSTOM
	} SDL_LogCategory;
*/
const (
	LOG_CATEGORY_APPLICATION = LogCategory(0)
	LOG_CATEGORY_ERROR       = LogCategory(1)
	LOG_CATEGORY_ASSERT      = LogCategory(2)
	LOG_CATEGORY_SYSTEM      = LogCategory(3)
	LOG_CATEGORY_AUDIO       = LogCategory(4)
	LOG_CATEGORY_VIDEO       = LogCategory(5)
	LOG_CATEGORY_RENDER      = LogCategory(6)
	LOG_CATEGORY_INPUT       = LogCategory(7)
	LOG_CATEGORY_TEST        = LogCategory(8)

	LOG_CATEGORY_RESERVED1  = LogCategory(9)
	LOG_CATEGORY_RESERVED2  = LogCategory(10)
	LOG_CATEGORY_RESERVED3  = LogCategory(11)
	LOG_CATEGORY_RESERVED4  = LogCategory(12)
	LOG_CATEGORY_RESERVED5  = LogCategory(13)
	LOG_CATEGORY_RESERVED6  = LogCategory(14)
	LOG_CATEGORY_RESERVED7  = LogCategory(15)
	LOG_CATEGORY_RESERVED8  = LogCategory(16)
	LOG_CATEGORY_RESERVED9  = LogCategory(17)
	LOG_CATEGORY_RESERVED10 = LogCategory(18)

	LOG_CATEGORY_CUSTOM = LogCategory(19)
)
